/** English chrome catalog; page content and fixture text are not UI strings. */
export const text = {
  otherTab: 'Colab is open in another tab.',
  useHere: 'Use here',
  oneTab: 'Only one tab per browser stays connected. Your work is saved.',
  ask: 'Ask agent',
  asks: 'Page asks',
  askSelection: 'Select text in the page to ask your agent.',
  askComment: 'Question or instruction',
  askPick: 'Choose an agent on your machine',
  askLoading: 'Loading your agents…',
  askNone: 'No agents are available on your machine.',
  askPreviewFailed: 'Could not prepare the preview. Refresh your agents and try again.',
  askRefresh: 'Refresh agents',
  askOffline: 'Your machine or page connection is offline. Reconnect and review a new preview.',
  askExpired: 'This preview has expired. Create a new preview before sending.',
  askRecheck: 'Re-check delivery',
  askAbandon: 'Abandon tracking',
  askActionFailed: 'Could not update this ask. Its delivery may still be uncertain.',
  askEmpty: 'No asks on this page yet.',
  askReply: 'Agent reply',
  askDeliveryAccepted: 'Accepted by your machine.',
  askReplyFrom: 'Reply from',
  askAgentLabel: 'Agent',
  askDeviceLabel: 'Asking device',
  askYou: 'You',
  askJustNow: 'Just now',
  askCreated: 'Ask created:',
  askDetails: 'Details',
  askOperation: 'Operation',
  askEmptyReply: 'The agent returned an empty reply.',
  askAbandoned: 'Tracking abandoned. The work may still have been delivered.',
  askExpiredState: 'This ask expired before delivery.',
  askDispatching: 'Sending to your machine…',
  askObservationUnavailable: 'Could not observe agent results. Re-check delivery to resume.',
  askOperationFailed: 'This send failed.',
  askFinalUnavailable: 'The agent result is unavailable.',
  askScopeDenied: 'Your Remote permission does not allow this ask.',
  askInputInvalid: 'Remote rejected this message. Create a new preview.',
  askRateLimited: 'Remote is busy. Review a fresh preview later.',
  askIntentConflict: 'This operation already has a different message. Create a new preview.',
  askRemoteClosed: 'Remote is closed. Reconnect and create a new preview.',
  askSessionEnded: 'Your Remote session ended. Create a fresh preview after the page reconnects.',
  askInputTooLarge: 'Remote rejected the message size. Create a shorter preview.',
  askStateUnavailable: 'Remote cannot read this operation yet. Re-check delivery later.',
  askCoreUnavailable: 'The agent service is unavailable. Re-check delivery later.',
  askPreview: 'Ask agent — preview',
  askMachine: 'Your machine',
  askAgent: 'Agent',
  askMessage: 'Exact message',
  askVisible: 'Your ask and the agent’s reply are visible to everyone who can see this page.',
  askHold: 'This send waits for approval on your machine.',
  askEscaped: 'Show hidden characters',
  askAdaptation:
    "Terminal delivery may escape '!' characters; the agent still receives the exact text above.",
  askUnavailable: 'Agent sending is unavailable for this page.',
  askSend: 'Send',
  askClose: 'Close preview',
  presenceOnline: 'Online',
  presenceOffline: 'Offline',
  presenceUnknown: 'Unknown',
  online: 'Online',
  offline: 'Offline',
  unknown: 'Online state unavailable',
  channel: 'Channel ready',
  paste: 'Paste only',
  not_ready: 'Not ready',
  not_running: 'Not running',
  deliveryUnknown: 'Delivery status unavailable',
  askPreparing: 'Preparing send…',
  askFailed: 'Could not prepare this send. Nothing was sent.',
  askHeld: 'Waiting for approval on your machine.',
  askAccepted: 'Accepted; awaiting the agent’s reply.',
  askUncertain: 'Delivery is uncertain. The work may have been delivered. Do not resend.',
  askRefused: 'The send was refused.',
  askCancelled: 'The send was cancelled.',
  export: 'Export page',
  download: 'Download',
  exportUnavailable: 'Export requires a verified paired page.',
  exportDiscussions: 'Discussions are not included.',
  exportPreparing: 'Preparing an exact copy of the verified page…',
  exportFailed:
    'Could not prepare or request this download. Already requested files may have downloaded.',
  exportReady: 'Download both files. This copy stays fixed while the live page changes.',
  exportPartial: 'One file requested. Download the other file to complete this copy.',
  exportRequested: 'Both downloads requested. Check your browser downloads for the saved files.',
  exportClose: 'Close export',
  product: 'Colab',
  local: 'Local preview',
  mounted: 'Paired space',
  mountedNote: 'Connected through your paired Remote session.',
  registering: 'Opening your paired space…',
  registrationFailed: 'Could not open this paired space. Reload to retry.',
  pinMismatch:
    'This address does not match the pinned space. Return to the original space address.',
  noWraps: 'This device has no verified page key yet. The page remains blocked.',
  save: 'Save source',
  saving: 'Saving…',
  editFailed:
    'The edit was not saved. Reopen the page to review the latest source before trying again.',
  ownNotDisplayed:
    'This page contains authenticated own data. Comments and activity are not displayed yet.',
  reload: 'Reload',
  pages: 'Pages',
  home: 'Space home',
  intro: 'A place for pages you share.',
  open: 'Open page',
  empty: 'No pages in this space yet.',
  private: 'Private',
  link: 'Link',
  public: 'Public',
  theme: 'Change color theme',
  source: 'Source',
  preview: 'Preview',
  loading: 'Opening page…',
  loaded: 'Live preview',
  boundary: 'Page content',
  error: 'Page unavailable',
  retry: 'Return to space',
  blocked: 'Preview stopped',
  navigation: 'The page navigated. Reopen it to continue.',
  failed: 'The renderer could not start. Reopen the page to try again.',
  limit: 'This preview accepts pages up to 2 MiB of HTML.',
  warning:
    'Page scripts run inside an isolated frame. A page can navigate its own frame; complete exfiltration prevention is not guaranteed.',
  adapter: 'This preview uses local sample pages. It is not connected to a remote space.',
} as const;
