# Generate runtime dependency notices, not developer/build-tool inventories.
# The HTTPS runtime adds ISC crypto code and CDLA-permissive root-certificate
# data. Preserve their complete generated texts and copyright notices.
accepted = ["MIT", "Apache-2.0", "Unicode-3.0", "ISC", "BSD-3-Clause", "CDLA-Permissive-2.0"]
ignore-dev-dependencies = true
ignore-build-dependencies = true
private = { ignore = true }
